### ISSUE TITLE
I'm Confusion

### ISSUE THREAD

**Issue by CoNFu51On** [Saramagrean/TKD_KWM-HD-Texture-Pack#10]
So the game is working fine, downloaded the texture packs but I can't seem to figure out where or what directory I should extract it to? send help

**Comment by Saramagrean** [comment]
extract to folder "PSP > TEXTURES > NPJH50878"

Btw, u can install texture pack direct via PPSSPP, just search texture pack zip file and press install.

**Comment by Saramagrean** [comment]
For Android, I recommended install this texture pack (.zip) via PPSSPP for improve loading performance.
