### ISSUE TITLE
Review the Hashing/Texture

### ISSUE THREAD

**Issue by Zinogre93** [Saramagrean/TKD_KWM-HD-Texture-Pack#2]
e.g.

Forbidden Set

Texture Replacement: Disable
![NPJH50878_00000](https://user-images.githubusercontent.com/75113791/100422862-088c4380-30c6-11eb-974c-a90bb9e020eb.jpg)

Texture Replacement: Enable
![NPJH50878_00001](https://user-images.githubusercontent.com/75113791/100422988-3d989600-30c6-11eb-9c1e-c4fc22f5b0b1.jpg)

Obviously, it is not the leg part of forbidden set (as it is not a black in color but a purple one), but the leg part of Erode set, which is like the purple variant of it.

**Comment by Saramagrean** [comment]
Okay, I will look into soon. 👌

**Comment by Saramagrean** [comment]
That armor set textures, grab for PC version. maybe it use a different style on PSP.

Sorry to keep you waiting. 😅
