### ISSUE TITLE
link

### ISSUE THREAD

**Issue by yomarh10** [Saramagrean/TKD_KWM-HD-Texture-Pack#4]
other link of the texture pack?

**Comment by Saramagrean** [comment]
It not complete yet, so i decided upload to another link after all progress finished.

**Comment by Saramagrean** [comment]
Some kind people in Toukiden Kiwami (PH), uploaded to another link.
https://drive.google.com/u/0/uc?id=1M98f2lVx8XGJqEMz4AU_MEzQJLmuEO90&export=download

**Comment by yomarh10** [comment]
yes i see it..thank you
