### ISSUE TITLE
blank after opening movie

### ISSUE THREAD

**Issue by crazyrexz** [Saramagrean/TKD_KWM-HD-Texture-Pack#6]
hi , im trying to manually patch english v3.0, i use iso v1.00 , with patch u post on main page, xdelta success, after the movie screen got flickering, im i do wrong? dlc use dlc 1.06 , and then use dlc from zipped english patch u give already. 

thanks

**Comment by Saramagrean** [comment]
Use DLC v1.07 and replace with DLC Mod from patch.

**Comment by crazyrexz** [comment]
okay , will try it , give you report later thanks

**Comment by crazyrexz** [comment]
thanks , it works


so clearly only need iso 1.00, then patch it with 3.0, put dlc 1.07, and finally put dlc inside patch 3.0
