### ISSUE TITLE
hidden story mode choices fix?

### ISSUE THREAD

**Issue by caledaca** [Saramagrean/TKD_KWM-HD-Texture-Pack#7]
I know it's something trivial, but is there any fix/workaround for the hidden choices in story mode bug? Thank you in advance 😅

**Comment by Saramagrean** [comment]
See, readme.

**Comment by dreamrar** [comment]
I know its rude to ask. But can you do something about that bug?. 

Thank you in advance😊

**Comment by Saramagrean** [comment]
I'm a not creater of this patch, (just help cutscenes part) can't do anything with this issue, sorry.
