### ISSUE TITLE
Slight Freeze

### ISSUE THREAD

**Issue by Hanuman211** [Saramagrean/TKD_KWM-HD-Texture-Pack#8]
I the texture packs, and every time I enter a new area or check something in the village, the game freezes for like 0.1 secs. At first I thought it was the game, but when I removed the texture pack, the game runs back normal again without freezing. It's not that much of a delay but it is kinda annoying when you check something on the village.

**Comment by Saramagrean** [comment]
Yeah, loading issue. I try convert all PNG to ZIM, maybe can help. It complete soon.

**Comment by Saramagrean** [comment]
Try ZIM Pack, May help reduce game freeze from loading textures.
- Main : https://bit.ly/3zuqwGK
- Addition update, replace with old files : https://bit.ly/3rt6gTj

for ZIM Pack req. PPSSPP v1.11.3 latest git build (694+)
u can donwload from here : https://buildbot.orphis.net/ppsspp

**Comment by Saramagrean** [comment]
Maybe this PR can help, I try it later.
https://github.com/hrydgard/ppsspp/pull/15025

**Comment by Cressdecay** [comment]
can you make a lite version texture pack using zim?

**Comment by Saramagrean** [comment]
> can you make a lite version texture pack using zim?

Wii do but KTX2 instead, because it better than ZIM.

**Comment by Saramagrean** [comment]
For Slight freeze issue, try KTX2 pack and If u use on Android platform, I recommended install this texture pack (.zip) via PPSSPP for improve loading performance.
