### ISSUE TITLE
UI and UHD graphics won't work

### ISSUE THREAD

**Issue by ALUKA69** [Saramagrean/TKD_KWM-HD-Texture-Pack#9]
I have downloaded the texture pack and extracted it in the right folder but still some japanese text like in the main menu and specially the item info, the story! I like to know the game but it seems it doesn't work for me at all. Maybe I missed something that causes the problem, is it the game or the emulator or the pack itself. Please helpp.

**Comment by CoNFu51On** [comment]
what exactly is the right folder?

**Comment by CoNFu51On** [comment]
> I have downloaded the texture pack and extracted it in the right folder but still some japanese text like in the main menu and specially the item info, the story! I like to know the game but it seems it doesn't work for me at all. Maybe I missed something that causes the problem, is it the game or the emulator or the pack itself. Please helpp.

what is the "right" folder?

**Comment by Saramagrean** [comment]
What's pack are u using? PNG or ZIM?

**Comment by Saramagrean** [comment]
Install this texture pack (.zip) via PPSSPP, It's the best option.
